version: '3.7'  # Docker Compose 파일 버전

services:
  zookeeper:  # Zookeeper 서비스 정의
    image: confluentinc/cp-zookeeper:latest  # Zookeeper의 최신 이미지를 사용
    environment:  # Zookeeper 환경 변수 설정
      ZOOKEEPER_CLIENT_PORT: 2181  # 클라이언트가 접속할 포트
      ZOOKEEPER_TICK_TIME: 2000  # Zookeeper tick time 설정 (밀리초)
      ZOO_MAX_CLIENT_CNXNS: 0  # 클라이언트 연결 최대 수 설정
      ZOO_LOG4J_PROP: "INFO, CONSOLE, ROLLINGFILE"  # 로그 레벨 및 로그 파일 설정
      ZOO_LOG_DIR: "/var/log/zookeeper"  # 로그 디렉토리 설정
      ZOO_JUTE_MAXBUFFER: 4194304  # jute.maxbuffer 설정 (예: 4MB)
    ports:
      - "2181:2181"  # 호스트의 2181 포트를 컨테이너의 2181 포트에 매핑
    volumes:
      - /Users/twocowsong/Documents/01.study/02.source/13.kafka/01.ymlfile/logs/zookeeper:/var/log/zookeeper  # 로컬 경로와 컨테이너 로그 경로를 연결

  kafka:  # Kafka 서비스 정의
    image: confluentinc/cp-kafka:latest  # Kafka의 최신 이미지를 사용
    container_name: confluentinc-kafka  # 컨테이너 이름을 confluentinc-kafka로 설정
    depends_on:  # Kafka 서비스가 시작되기 전에 Zookeeper 서비스가 시작되어야 함
      - zookeeper
    ports:
      - "9092:9092"  # 호스트의 9092 포트를 컨테이너의 9092 포트에 매핑
      - "29092:29092"  # 호스트의 29092 포트를 컨테이너의 29092 포트에 매핑
    environment:  # Kafka 환경 변수 설정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Kafka가 연결할 Zookeeper의 주소와 포트
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092  # Kafka 리스너 설정
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092  # 클라이언트가 접속할 광고된 리스너 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # 보안 프로토콜 맵핑 설정
      KAFKA_BROKER_ID: 1  # Kafka 브로커 ID 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # 오프셋 토픽의 복제 인수 설정
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # 트랜잭션 상태 로그의 최소 ISR 설정
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # 트랜잭션 상태 로그의 복제 인수 설정
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000  # 로그 플러시 간격 설정 (메시지 수 기준)
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0  # 그룹 초기 리밸런스 지연 시간 설정 (밀리초)
    volumes:
      - /Users/twocowsong/Documents/01.study/02.source/13.kafka/01.ymlfile/logs/kafka:/var/log/kafka  # 로컬 경로와 컨테이너 로그 경로를 연결

volumes:
  kafka-logs:
  zookeeper-logs:

